-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local browser = "vivaldi --enable-features=UseOzonePlatform --ozone-platform=wayland"
local editor = "code --disable-gpu"
local fileManager = term .. " --class \"tuiFileManager\" -e yazi"
local mainMod = "SUPER"
local term = "/nix/store/pdhdg4bm1l14alah1ay4rwd3g7f6l0pd-kitty-0.47.1/bin/kitty"
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("md3_standard", { type = "bezier", points = { { 0.2, 0 }, { 0, 1 } } })
hl.curve("md3_decel", { type = "bezier", points = { { 0.05, 0.7 }, { 0.1, 1 } } })
hl.curve("md3_accel", { type = "bezier", points = { { 0.3, 0 }, { 0.8, 0.15 } } })
hl.curve("overshot", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.1 } } })
hl.curve("crazyshot", { type = "bezier", points = { { 0.1, 1.5 }, { 0.76, 0.92 } } })
hl.curve("hyprnostretch", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.0 } } })
hl.curve("fluent_decel", { type = "bezier", points = { { 0.1, 1 }, { 0, 1 } } })
hl.curve("easeInOutCirc", { type = "bezier", points = { { 0.85, 0 }, { 0.15, 1 } } })
hl.curve("easeOutCirc", { type = "bezier", points = { { 0, 0.55 }, { 0.45, 1 } } })
hl.curve("easeOutExpo", { type = "bezier", points = { { 0.16, 1 }, { 0.3, 1 } } })
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 3,
    bezier = "md3_decel",
    style = "popin 60%",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 10,
    bezier = "default",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 2.5,
    bezier = "md3_decel",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 3.5,
    bezier = "easeOutExpo",
    style = "slide",
})
hl.animation({
    leaf = "specialWorkspace",
    enabled = true,
    speed = 3,
    bezier = "md3_decel",
    style = "slidevert",
})

hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.exec_cmd("hyprctl activewindow | grep pid | tr -d 'pid:' | xargs kill"))
hl.bind(mainMod .. " + W", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + SHIFT + G", hl.dsp.group.toggle())
hl.bind("ALT + return", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(mainMod .. " + ALT + L", hl.dsp.exec_cmd("hyprlock"))
hl.bind(mainMod .. " + backspace", hl.dsp.exit())
hl.bind(mainMod .. " + delete", hl.dsp.exec_cmd("systemctl reboot"))
hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(term))
hl.bind(mainMod .. " + F", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + C", hl.dsp.exec_cmd(editor))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(browser))
hl.bind(CONTROL .. " + ALT + DELETE", hl.dsp.exec_cmd(term .. " -e '/nix/store/d2a48mxsm97f6p63yzrs8h50xp9ifcqj-btop-1.4.7/bin/btop'"))
hl.bind(mainMod .. " + CTRL + C", hl.dsp.exec_cmd("hyprpicker --autocopy --format=hex"))
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd("noctalia-shell ipc call launcher toggle"))
hl.bind(mainMod .. " + G", hl.dsp.exec_cmd("launcher games"))
hl.bind("xf86Sleep", hl.dsp.exec_cmd("systemctl suspend"))
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("pamixer --default-source -t"))
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("pamixer -t"))
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"))
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"))
hl.bind("xf86AudioNext", hl.dsp.exec_cmd("playerctl next"))
hl.bind("xf86AudioPrev", hl.dsp.exec_cmd("playerctl previous"))
hl.bind(mainMod .. " + Tab", hl.dsp.window.cycle_next({ next = true }))
hl.bind(mainMod .. " + Tab", hl.dsp.window.bring_to_top())
hl.bind(mainMod .. " + CTRL + right", hl.dsp.focus({ workspace = "r+1" }))
hl.bind(mainMod .. " + CTRL + left", hl.dsp.focus({ workspace = "r-1" }))
hl.bind(mainMod .. " + CTRL + down", hl.dsp.focus({ workspace = "empty" }))
hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + ALT + left", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainMod .. " + ALT + right", hl.dsp.window.move({ direction = "r" }))
hl.bind(mainMod .. " + ALT + up", hl.dsp.window.move({ direction = "u" }))
hl.bind(mainMod .. " + ALT + down", hl.dsp.window.move({ direction = "d" }))
hl.bind(mainMod .. " + CTRL + ALT + left", hl.dsp.window.swap({ direction = "l" }))
hl.bind(mainMod .. " + CTRL + ALT + right", hl.dsp.window.swap({ direction = "r" }))
hl.bind(mainMod .. " + CTRL + ALT + up", hl.dsp.window.swap({ direction = "u" }))
hl.bind(mainMod .. " + CTRL + ALT + down", hl.dsp.window.swap({ direction = "d" }))
hl.bind(mainMod .. " + CTRL + Z", hl.dsp.window.move({ workspace = "special", follow = false }))
hl.bind(mainMod .. " + SHIFT + Z", hl.dsp.window.move({ workspace = "special" }))
hl.bind(mainMod .. " + Z", hl.dsp.workspace.toggle_special(""))
hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + CTRL + 1", hl.dsp.window.move({ workspace = 1, follow = false }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + CTRL + 2", hl.dsp.window.move({ workspace = 2, follow = false }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + CTRL + 3", hl.dsp.window.move({ workspace = 3, follow = false }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + CTRL + 4", hl.dsp.window.move({ workspace = 4, follow = false }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + CTRL + 5", hl.dsp.window.move({ workspace = 5, follow = false }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + CTRL + 6", hl.dsp.window.move({ workspace = 6, follow = false }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + CTRL + 7", hl.dsp.window.move({ workspace = 7, follow = false }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + CTRL + 8", hl.dsp.window.move({ workspace = 8, follow = false }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + CTRL + 9", hl.dsp.window.move({ workspace = 9, follow = false }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))
hl.bind(mainMod .. " + CTRL + 0", hl.dsp.window.move({ workspace = 10, follow = false }))

hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.resize({ x = 100, y = 0, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + left", hl.dsp.window.resize({ x = -100, y = 0, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + up", hl.dsp.window.resize({ x = 0, y = -100, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + down", hl.dsp.window.resize({ x = 0, y = 100, relative = true }), { repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 2%-"), { repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set +2%"), { repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("pamixer -d 2"), { repeating = true })
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("pamixer -i 2"), { repeating = true })

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
-- TODO: manual review — malformed env on line 148: GDK_BACKEND,wayland,x11,*
hl.env("NIXOS_OZONE_WL", "1")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")
hl.env("MOZ_ENABLE_WAYLAND", "1")
hl.env("OZONE_PLATFORM", "wayland")
hl.env("EGL_PLATFORM", "wayland")
hl.env("CLUTTER_BACKEND", "wayland")
hl.env("SDL_VIDEODRIVER", "wayland")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("QT_ENABLE_HIGHDPI_SCALING", "1")
hl.env("WLR_RENDERER_ALLOW_SOFTWARE", "1")
hl.env("NIXPKGS_ALLOW_UNFREE", "1")

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace",
})

hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = "1",
})

hl.window_rule({
    match = {
        title = "(.*)(Godot)(.*)$",
    },
    float = false,
})

hl.window_rule({
    match = {
        class = "^(firefox|Brave-browser|floorp|zen|zen-beta)$",
    },
    opacity = "1.00 1.00",
})

hl.window_rule({
    match = {
        class = "^(Emacs)$",
    },
    opacity = "0.90 0.80",
})

hl.window_rule({
    match = {
        class = "^(gcr-prompter)$",
    },
    opacity = "0.90 0.80",
})

hl.window_rule({
    match = {
        title = "^(Hyprland Polkit Agent)$",
    },
    opacity = "0.90 0.80",
})

hl.window_rule({
    match = {
        class = "^(obsidian)$",
    },
    opacity = "0.90 0.80",
})

hl.window_rule({
    match = {
        class = "^(Lutris|lutris|net.lutris.Lutris)$",
    },
    opacity = "0.90 0.80",
})

hl.window_rule({
    match = {
        class = "^(kitty|alacritty|Alacritty|org.wezfurlong.wezterm)$",
    },
    opacity = "0.80 0.70",
})

hl.window_rule({
    match = {
        class = "^(nvim-wrapper)$",
    },
    opacity = "0.80 0.70",
})

hl.window_rule({
    match = {
        class = "^(gnome-disks)$",
    },
    opacity = "0.80 0.70",
})

hl.window_rule({
    match = {
        class = "^(org.gnome.Nautilus|Thunar|thunar|pcmanfm)$",
    },
    opacity = "0.80 0.70",
})

hl.window_rule({
    match = {
        class = "^(thunar-volman-settings)$",
    },
    opacity = "0.80 0.70",
})

hl.window_rule({
    match = {
        class = "^(org.gnome.FileRoller)$",
    },
    opacity = "0.80 0.70",
})

hl.window_rule({
    match = {
        class = "^(io.github.ilya_zlobintsev.LACT)$",
    },
    opacity = "0.80 0.70",
})

hl.window_rule({
    match = {
        class = "^(Steam|steam|steamwebhelper)$",
    },
    opacity = "0.80 0.70",
})

hl.window_rule({
    match = {
        class = "^(Spotify|spotify)$",
    },
    opacity = "0.80 0.70",
})

hl.window_rule({
    match = {
        title = "(.*)(Spotify)(.*)$",
    },
    opacity = "0.80 0.70",
})

hl.window_rule({
    match = {
        title = "^(Kvantum Manager)$",
    },
    opacity = "0.80 0.70",
})

hl.window_rule({
    match = {
        class = "^(VSCodium|codium-url-handler)$",
    },
    opacity = "0.80 0.70",
})

hl.window_rule({
    match = {
        class = "^(code|code-url-handler)$",
    },
    opacity = "0.80 0.70",
})

hl.window_rule({
    match = {
        class = "^(tuiFileManager)$",
    },
    opacity = "0.80 0.70",
})

hl.window_rule({
    match = {
        class = "^(org.kde.dolphin)$",
    },
    opacity = "0.80 0.70",
})

hl.window_rule({
    match = {
        class = "^(org.kde.ark)$",
    },
    opacity = "0.80 0.70",
    float = true,
})

hl.window_rule({
    match = {
        class = "^(nwg-look)$",
    },
    opacity = "0.80 0.70",
    float = true,
})

hl.window_rule({
    match = {
        class = "^(qt5ct|qt6ct)$",
    },
    opacity = "0.80 0.70",
})

hl.window_rule({
    match = {
        class = "^(yad)$",
    },
    opacity = "0.80 0.70",
    float = true,
})

hl.window_rule({
    match = {
        class = "^(discord)$",
    },
    opacity = "0.90 0.80",
})

hl.window_rule({
    match = {
        class = "^(WebCord)$",
    },
    opacity = "0.90 0.80",
})

hl.window_rule({
    match = {
        class = "^(com.github.rafostar.Clapper)$",
    },
    opacity = "0.90 0.80",
    float = true,
})

hl.window_rule({
    match = {
        class = "^(com.github.tchx84.Flatseal)$",
    },
    opacity = "0.80 0.70",
})

hl.window_rule({
    match = {
        class = "^(hu.kramo.Cartridges)$",
    },
    opacity = "0.80 0.70",
})

hl.window_rule({
    match = {
        class = "^(com.obsproject.Studio)$",
    },
    opacity = "0.80 0.70",
})

hl.window_rule({
    match = {
        class = "^(gnome-boxes)$",
    },
    opacity = "0.80 0.70",
})

hl.window_rule({
    match = {
        class = "^(app.drey.Warp)$",
    },
    opacity = "0.80 0.70",
    float = true,
})

hl.window_rule({
    match = {
        class = "^(net.davidotek.pupgui2)$",
    },
    opacity = "0.80 0.70",
    float = true,
})

hl.window_rule({
    match = {
        class = "^(Signal)$",
    },
    opacity = "0.80 0.70",
    float = true,
})

hl.window_rule({
    match = {
        class = "^(io.gitlab.theevilskeleton.Upscaler)$",
    },
    opacity = "0.80 0.70",
    float = true,
})

hl.window_rule({
    match = {
        class = "^(pavucontrol)$",
    },
    opacity = "0.80 0.70",
    float = true,
})

hl.window_rule({
    match = {
        class = "^(org.pulseaudio.pavucontrol)$",
    },
    opacity = "0.80 0.70",
})

hl.window_rule({
    match = {
        class = "^(blueman-manager)$",
    },
    opacity = "0.80 0.70",
    float = true,
})

hl.window_rule({
    match = {
        class = "^(.blueman-manager-wrapped)$",
    },
    opacity = "0.80 0.70",
    float = true,
})

hl.window_rule({
    match = {
        class = "^(nm-applet)$",
    },
    opacity = "0.80 0.70",
    float = true,
})

hl.window_rule({
    match = {
        class = "^(nm-connection-editor)$",
    },
    opacity = "0.80 0.70",
    float = true,
})

hl.window_rule({
    match = {
        class = "^(org.kde.polkit-kde-authentication-agent-1)$",
    },
    opacity = "0.80 0.70",
    float = true,
})

hl.window_rule({
    match = {
        title = "^(Picture-in-Picture)$",
        class = "^(zen|zen-beta|floorp|firefox)$",
    },
    float = true,
    pin = true,
})

hl.window_rule({
    match = {
        tag = "games",
    },
    content = "game",
    sync_fullscreen = true,
    fullscreen = true,
    border_size = 1,
    no_shadow = true,
    no_blur = true,
    no_anim = true,
})

hl.window_rule({
    match = {
        content = "game",
    },
    tag = "+games",
})

hl.window_rule({
    match = {
        class = "^(steam_app.*|steam_app_d+)$",
    },
    tag = "+games",
})

hl.window_rule({
    match = {
        class = "^(gamescope)$",
    },
    tag = "+games",
})

hl.window_rule({
    match = {
        class = "(Waydroid)",
    },
    tag = "+games",
})

hl.window_rule({
    match = {
        class = "(osu!)",
    },
    tag = "+games",
})

hl.window_rule({
    match = {
        class = "^(qt5ct)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(eog)$",
    },
    float = true,
})

hl.workspace_rule({
    workspace = "1",
    default = true,
})

hl.config({
    animations = {
        enabled = true,
    },
    binds = {
        workspace_back_and_forth = 0,
    },
    decoration = {
        blur = {
            enabled = true,
            ignore_opacity = true,
            new_optimizations = true,
            passes = 2,
            size = 6,
            special = true,
            xray = false,
        },
        shadow = {
            enabled = false,
        },
        dim_special = 0.300000,
        rounding = 10,
    },
    dwindle = {
        preserve_split = true,
    },
    ecosystem = {
        no_donation_nag = true,
    },
    general = {
        border_size = 2,
        col = {
            active_border = { colors = { "rgba(ca9ee6ff)", "rgba(f2d5cfff)" }, angle = 45 },
            inactive_border = { colors = { "rgba(b4befecc)", "rgba(6c7086cc)" }, angle = 45 },
        },
        gaps_in = 4,
        gaps_out = 8,
        layout = "master",
        resize_on_border = true,
    },
    group = {
        col = {
            border_active = { colors = { "rgba(ca9ee6ff)", "rgba(f2d5cfff)" }, angle = 45 },
            border_inactive = { colors = { "rgba(b4befecc)", "rgba(6c7086cc)" }, angle = 45 },
            border_locked_active = { colors = { "rgba(ca9ee6ff)", "rgba(f2d5cfff)" }, angle = 45 },
            border_locked_inactive = { colors = { "rgba(b4befecc)", "rgba(6c7086cc)" }, angle = 45 },
        },
    },
    input = {
        tablet = {
            output = "current",
        },
        touchpad = {
            natural_scroll = false,
        },
        follow_mouse = 1,
        force_no_accel = true,
        kb_layout = "us,ru",
        kb_variant = "intl,",
        numlock_by_default = true,
        repeat_delay = 275,
        repeat_rate = 35,
        sensitivity = 0,
    },
    master = {
        mfact = 0.500000,
        new_on_top = true,
        new_status = "master",
    },
    misc = {
        disable_hyprland_logo = true,
        enable_swallow = true,
        mouse_move_focuses_monitor = true,
        swallow_regex = "^(Alacritty|kitty)$",
        vrr = 2,
    },
    render = {
        direct_scanout = 0,
    },
    xwayland = {
        force_zero_scaling = false,
    },
})

hl.on("hyprland.start", function()
    hl.exec_cmd("/nix/store/ai8mmqghspvnhv2jz12pfg6b6dqmg3b3-dbus-1.16.2/bin/dbus-update-activation-environment --systemd --all && systemctl --user stop hyprland-session.target && systemctl --user start hyprland-session.target")
    hl.exec_cmd("noctalia-shell")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("/nix/store/vg8g4zbkx0qbxzpfb4mldlcpqwzfvsr7-wl-clipboard-2.3.0/bin/wl-paste --type text --watch cliphist store")
    hl.exec_cmd("/nix/store/vg8g4zbkx0qbxzpfb4mldlcpqwzfvsr7-wl-clipboard-2.3.0/bin/wl-paste --type image --watch cliphist store")
    hl.exec_cmd("rm '$XDG_CACHE_HOME/cliphist/db'")
    hl.exec_cmd("polkit-agent-helper-1")
    hl.exec_cmd("nextcloud --background")
    hl.exec_cmd("netbird-ui")
    hl.exec_cmd("/nix/store/khvj4lqxwpc9m9py0irjf6ishhscq66x-steam-1.0.0.85/bin/steam -silent")
    hl.exec_cmd("/nix/store/q0d60wh8ibkzr8l1ixqvhfkm7nnxi26v-heroic-2.22.0/bin/heroic")
    hl.exec_cmd("Enpass -minimize")
end)

